name: animated_background
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: ">=2.8.0 <3.0.0"
dependencies:
  http: 0.12.2
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  shared_preferences: 0.5.12+2
  animated_splash_screen: ^1.0.1+2
  lottie: ^0.7.0+1
  splashscreen: ^1.2.0
  convex_bottom_bar: ^2.6.0
  bottom_navy_bar: ^5.5.0
  stacked: ^1.7.6
  flutter_launcher_icons: ^0.8.1
  font_awesome_flutter: ^8.5.0
  toast: ^0.1.5
  intl: ^0.16.0
  flutter_spinkit: "^4.1.2"
  progress_dialog: ^1.2.4
  getwidget: ^1.2.4
  chips_choice: ^2.0.1
  empty_widget: ^0.0.1-dev.1
  qr_flutter: ^4.0.0
  qr_code_scanner: ^0.4.0
  dropdown_search: ^0.5.0
  dio: ^3.0.10

  settings_ui: ^1.0.0
  permission_handler: ^5.1.0+2
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
  - lib/resources/images/background.png
  - lib/resources/images/logo.png
  - lib/resources/images/icon-back.png
  - lib/resources/images/im_emptyIcon_2.png
  - lib/resources/images/profile_header_background.png
  - lib/resources/images/
  - lib/resources/lottie/
  - assets/fitness_app/
  - assets/images/
  - lib/resources/images/warn.png
module:
  androidX: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/resources/images/ssc2.png"